#!/usr/bin/env bash
# Idempotent one-paste setup for pii_redactor_lightening.
#
# Installs a runnable, self-contained copy under ~/.local (not TCC-protected),
# so external Shortcut triggers (hotkey, BackgroundShortcutRunner) can execute
# the launcher even if the repo was cloned under Desktop/Documents/Downloads.
#
# What this creates:
#   $PII_REDACTOR_HOME/.venv          (self-contained venv, non-editable install)
#   $PII_REDACTOR_HOME/model_prewarm  (model cache marker)
#   ~/.local/bin/pii-redact-clipboard (launcher; what the Shortcut calls)
#
# Env overrides:
#   PII_REDACTOR_HOME  (default: ~/.local/share/pii-redactor)
#
# Safe to re-run: each step is a no-op once it has succeeded.

set -euo pipefail

# Resolve repo root regardless of CWD so this works as `bash scripts/bootstrap.sh`.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

INSTALL_DIR="${PII_REDACTOR_HOME:-$HOME/.local/share/pii-redactor}"
LAUNCHER_DIR="$HOME/.local/bin"
LAUNCHER="$LAUNCHER_DIR/pii-redact-clipboard"

echo "==> [1/5] Verifying uv is installed"
if ! command -v uv >/dev/null 2>&1; then
  echo "ERROR: uv is not installed. Install it first:" >&2
  echo "  curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
  exit 1
fi
echo "    uv: $(uv --version)"
echo "    install dir: $INSTALL_DIR"
echo "    launcher:    $LAUNCHER"

echo "==> [2/5] Creating self-contained venv at $INSTALL_DIR/.venv"
mkdir -p "$INSTALL_DIR"
if [ -x "$INSTALL_DIR/.venv/bin/python" ]; then
  echo "    venv already exists, reusing"
else
  uv venv "$INSTALL_DIR/.venv"
fi

echo "==> [3/5] Installing package (non-editable) into venv"
# Non-editable: copies code into the venv. The repo clone is no longer needed
# at runtime, so clone location (Desktop/etc.) becomes irrelevant for execution.
uv pip install --python "$INSTALL_DIR/.venv/bin/python" "$REPO_ROOT" >/dev/null

echo "==> [4/5] Prewarming GLiNER2 model cache (~1 GB, one-time)"
if "$INSTALL_DIR/.venv/bin/python" -c "from redactor import model_redactor; model_redactor._load_model(model_redactor.DEFAULT_MODEL_ID)" 2>/dev/null; then
  touch "$INSTALL_DIR/model_prewarm"
  echo "    model cached"
else
  echo "ERROR: model prewarm failed." >&2
  echo "Check your network connection and re-run this script." >&2
  exit 1
fi

echo "==> [5/5] Writing launcher at $LAUNCHER"
mkdir -p "$LAUNCHER_DIR"
# Direct exec of the venv console script. No `uv run`, no `cd`, no PATH juggling
# beyond what the launcher itself sets. This is what the Shortcut calls.
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by pii_redactor_lightening bootstrap.sh.
# Thin launcher for the Apple Shortcut "Redact PII" and direct CLI use.
# Do not edit by hand; re-run scripts/bootstrap.sh to regenerate.
set -euo pipefail
export PII_REDACTOR_HOME="\${PII_REDACTOR_HOME:-$INSTALL_DIR}"
export PATH="\$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
exec "\$PII_REDACTOR_HOME/.venv/bin/redact-clipboard" run
EOF
chmod +x "$LAUNCHER"

cat <<EOF

==> Setup complete.

Next steps:
  1. Build and import the Apple Shortcut (see README.md):
         uv run python scripts/build_shortcut.py
         open "dist/Redact PII.shortcut"

  2. In Shortcuts.app, assign a global keyboard shortcut to it
     (info (i) button -> Add Keyboard Shortcut).

  3. Add Shortcuts.app to System Settings -> General -> Login Items
     so the hotkey works without manually launching the app.

  4. Direct CLI fallback (works from anywhere):
         $LAUNCHER
EOF
